version: "3.8"
services:
    translation-server:
        build: ..
        environment:
            FLASK_APP: /code/server.py
            FLASK_ENV: development
            ENV: development
        # run the development server
        entrypoint: [ "flask", "run" ]
        volumes:
            - ..:/code
        ports:
            - 5000:5000